Profile, profilePreview, MyApp changes
mushu-bytes/pickup pull request #12
Opened 2024-03-12 18:11 UTC by Apoak

2024-03-12 18:27 UTC, isaacschiffler requested changes
Base level looks good. If time permits, maybe edit so it uses the backend server and draws from the user database?

2024-03-12 18:27 UTC, isaacschiffler commented on packages/react-frontend/src/MyApp.js
> +        <ProfileForm handleSubmit ={UpdateProfileList}/>
this looks good

2024-03-12 18:27 UTC, isaacschiffler commented on packages/react-frontend/src/MyApp.js
> +    const promise = fetch("http://localhost:8000/profile", {
Edit this to use the user database instead of a new profiles database with the API_URL backend server?

2024-03-12 18:27 UTC, isaacschiffler commented on packages/react-frontend/src/MyApp.js
> +  const profileData = {
Take this out if it works with the backend?

2024-03-12 18:27 UTC, isaacschiffler commented on packages/react-frontend/src/profile.js
good i think

2024-03-13 03:20 UTC, mushu-bytes approved these changes

2024-03-13 03:21 UTC, merged